#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Eu sei que isso é chato só que deu ruim aqui com PHPSTAN... 😉";
    exit 1;
fi;

# rodar os testes
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Não é que eu seja ruiom mas deu ruim aqui com algum teste... :^)";
    exit 1;
fi;

exit 0;