name: Laravel CI/CD

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Install Node.js dependencies
      run: npm install

    - name: Directory Permissions
      run: chmod -R 755 storage bootstrap/cache

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Set up Sail
      run: ./vendor/bin/sail up -d

    - name: Generate key
      run: ./vendor/bin/sail artisan key:generate

    - name: Wait for MySQL to be ready
      run: ./vendor/bin/sail exec mysql bash -c 'while ! mysqladmin ping -h"mysql" --silent; do sleep 1; done'

    - name: Run database migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Run tests
      run: ./vendor/bin/sail artisan test

    - name: Execute Larastan
      run: ./vendor/bin/sail exec laravel.test ./vendor/bin/phpstan analyse

    - name: Execute Laravel Pint
      run: ./vendor/bin/sail exec laravel.test ./vendor/bin/pint --test

    - name: Notify Slack on Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  
