name: CI

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Install Node.js dependencies
      run: npm install

    - name: Directory Permissions
      run: chmod -R 755 storage bootstrap/cache

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: ./vendor/bin/sail artisan key:generate

    - name: Run Sail
      run: ./vendor/bin/sail up -d

    - name: Wait for MySQL to be ready
      run: ./vendor/bin/sail exec mysql bash -c 'while ! mysqladmin ping -h"mysql" --silent; do sleep 1; done'

    - name: Run database migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Run tests
      run: ./vendor/bin/sail artisan test

    - name: Execute Larastan
      run: ./vendor/bin/sail phpstan analyse

    - name: Execute Laravel Pint
      run: ./vendor/bin/sail pint --test